---
apiVersion: v2
name: adminer
appVersion: 4.8.1
version: 0.2.0
description: Adminer is a full-featured database management tool written in PHP. Conversely to phpMyAdmin, it consist of a single file ready to deploy to the target server. Adminer is available for MySQL, MariaDB, PostgreSQL, SQLite, MS SQL, Oracle, Firebird, SimpleDB, Elasticsearch and MongoDB
home: https://www.adminer.org
icon: https://raw.githubusercontent.com/Kong/docker-official-docs/master/adminer/logo.png
keywords:
  - adminer
  - postgres
  - mysql
  - sqlite
  - elasticsearch
  - mongodb
  - database
  - sql
source:
  - https://github.com/cetic/helm-adminer
maintainers:
  - name: fzalila
    email: faiez.zalila@cetic.be
    url: https://github.com/fzalila
  - name: alexnuttinck
    email: alexandre.nuttinck@cetic.be
    url: https://github.com/alexnuttinck
